[project]
name = "taskbadger-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "invoke",
    "mkdocs-material",
    "mkdocstrings[python]",
    "ruff>=0.9.6",
]
