name: docs-deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: docs
      - uses: actions/checkout@v4
        with:
          repository: taskbadger/taskbadger-python
          path: taskbadger-python
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Install project
        run: |
          cd docs
          uv sync --frozen
      - run: |
          cd docs
          uv run mkdocs gh-deploy --force
